name: art
description: "A new Flutter project."
publish_to: 'none' # Keep this line if you don't plan to publish it

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (compatible versions for SDK >=3.2.3)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # Bluetooth thermal printer
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  flutter_spinkit: ^5.2.0  # or the latest version
  # Cupertino icons for iOS
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  # Shared preferences for local storage
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  # Secure local storage for tokens, if needed
  flutter_secure_storage: ^9.0.0
  csv: ^5.0.0    # State management (optional but useful)
  provider: ^6.1.2
  path_provider: ^2.1.2
  flutter_speed_dial: ^7.0.0
  lucide_icons: ^0.257.0
  # Date formatting
  intl: ^0.19.0
  flutter_animate: ^4.2.0
  fl_chart: ^0.63.0
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.2
  dropdown_button2: ^1.0.0
  collection: ^1.18.0
  fluttertoast: ^8.0.9
  flutter_bluetooth_serial: ^0.4.0  # For scanning & connecting via Bluetooth
  esc_pos_utils_plus: ^2.0.1+6
  blue_thermal_printer: ^1.1.5      # OR use this if you want everything in one package (Android only)
  share_plus: ^7.2.2
  animations: ^2.0.7
88dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#  assets:
#    - images/logo.png

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
