import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:provider/provider.dart';
import 'providers/user_provider.dart'; // Your UserProvider
import 'screens/login_screen.dart'; // Your login screen
import 'package:cloud_firestore/cloud_firestore.dart';
import 'screens/product_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ✅ Enable Firestore offline persistence
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => UserProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Using the branchCode to determine the home screen
    return MaterialApp(
      title: 'Arthaa',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.indigo,
      ),
      home: Consumer<UserProvider>(
        builder: (context, userProvider, child) {
          // If branchCode is available, go to the home screen (ProductScreen or similar)
          if (userProvider.branchCode != null) {
            return ProductScreen(); // Replace with your actual screen
          } else {
            return LoginScreen(); // If no branchCode, show login screen
          }
        },
      ),
    );
  }
}
